import { storage } from "./storage";
import type { InsertPlace } from "@shared/schema";

const seedPlaces: InsertPlace[] = [
  {
    name: "The Dog & Duck",
    address: "12 High Street",
    town: "Oxford",
    postcode: "OX1 4AA",
    category: "pub",
    description: "A traditional Oxford pub with a warm welcome for dogs of all sizes. Our flagstone floors and roaring fire make it the perfect spot after a countryside walk. Dogs get their own biscuit tin at the bar.",
    phone: "01865 123456",
    website: "https://dogandduck-oxford.co.uk",
    imageUrl: "/images/pub1.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: false,
    latitude: 51.7520,
    longitude: -1.2577,
    rating: 4.8,
    reviewCount: 124,
  },
  {
    name: "Brew & Biscuit",
    address: "5 Market Place",
    town: "Oxford",
    postcode: "OX1 3HB",
    category: "cafe",
    description: "Oxford's most dog-friendly café. We serve artisan coffee alongside a special dog menu featuring homemade pupcakes and dog-safe treats. Water stations on every table.",
    phone: "01865 987654",
    website: "https://brewandbiscuit.co.uk",
    imageUrl: "/images/cafe1.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.7535,
    longitude: -1.2540,
    rating: 4.9,
    reviewCount: 203,
  },
  {
    name: "The Riverside Kitchen",
    address: "1 Riverside Walk",
    town: "Oxford",
    postcode: "OX2 6BN",
    category: "restaurant",
    description: "Enjoy fine dining beside the Thames with your four-legged companion. Dogs are welcomed in our riverside terrace area. We always have fresh water available and often have treats behind the bar.",
    phone: "01865 555123",
    website: "https://riversidekitchen.co.uk",
    imageUrl: "/images/restaurant1.jpg",
    dogPolicy: "dogs_outside",
    waterBowls: true,
    dogTreats: false,
    dogMenu: false,
    latitude: 51.7480,
    longitude: -1.2632,
    rating: 4.5,
    reviewCount: 89,
  },
  {
    name: "Paws & Pints",
    address: "22 Bath Road",
    town: "Swindon",
    postcode: "SN1 4AU",
    category: "pub",
    description: "Swindon's original dog-friendly pub. We host monthly dog meetups, and our garden is fully enclosed so your dog can roam free. Full dog menu available including birthday cakes on request.",
    phone: "01793 456789",
    website: "https://pawsandpints.co.uk",
    imageUrl: "/images/pub2.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.5632,
    longitude: -1.7832,
    rating: 4.7,
    reviewCount: 156,
  },
  {
    name: "Hounds Coffee House",
    address: "8 Regent Street",
    town: "Swindon",
    postcode: "SN1 1JL",
    category: "cafe",
    description: "A café that truly loves dogs. Find a dedicated dog corner with beds, toys and water. Our baristas know how to make a 'puppuccino' and we sell dog-friendly pastries every weekend.",
    phone: "01793 778899",
    website: "https://houndscoffee.co.uk",
    imageUrl: "/images/cafe2.jpg",
    dogPolicy: "dogs_inside",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.5595,
    longitude: -1.7840,
    rating: 4.6,
    reviewCount: 77,
  },
  {
    name: "The Leash & Larder",
    address: "45 George Street",
    town: "Bath",
    postcode: "BA1 2EH",
    category: "restaurant",
    description: "A charming restaurant in the heart of Bath where dogs are genuinely celebrated. Our chef creates a weekly rotating dog menu, and dogs eat free on Sundays. Resident dog Barley says hello.",
    phone: "01225 334455",
    website: "https://leashandlarder.co.uk",
    imageUrl: "/images/restaurant2.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.3800,
    longitude: -2.3600,
    rating: 4.9,
    reviewCount: 311,
  },
  {
    name: "Roman Bath Outfitters",
    address: "7 Union Street",
    town: "Bath",
    postcode: "BA1 1RH",
    category: "retail",
    description: "Independent outdoor and lifestyle store welcoming dogs on leads throughout. Browse our range of walking gear, home goods and gifts with your canine companion by your side.",
    phone: "01225 667788",
    website: "https://romanbathoutfitters.co.uk",
    imageUrl: "/images/retail1.jpg",
    dogPolicy: "dogs_inside",
    waterBowls: true,
    dogTreats: false,
    dogMenu: false,
    latitude: 51.3825,
    longitude: -2.3635,
    rating: 4.3,
    reviewCount: 42,
  },
  {
    name: "The Woofington Arms",
    address: "3 Church Lane",
    town: "Bristol",
    postcode: "BS1 5TR",
    category: "pub",
    description: "Bristol's best kept secret for dog lovers. This cosy pub has a dedicated dog area with raised beds and natural toys. Dog birthdays celebrated for free with a pupcake and a photo!",
    phone: "0117 923 4567",
    website: "https://woofingtonarms.co.uk",
    imageUrl: "/images/pub3.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.4545,
    longitude: -2.5879,
    rating: 4.8,
    reviewCount: 198,
  },
  {
    name: "Clifton Coffee Roasters",
    address: "12 Princess Victoria Street",
    town: "Bristol",
    postcode: "BS8 4BX",
    category: "cafe",
    description: "Award-winning specialty coffee roasters in Clifton. Dogs are welcome inside and on our sunny terrace. We keep dog biscuits behind the counter and always have a fresh bowl of water waiting.",
    phone: "0117 946 7890",
    website: "https://cliftoncoffeeroasters.co.uk",
    imageUrl: "/images/cafe3.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: false,
    latitude: 51.4590,
    longitude: -2.6151,
    rating: 4.7,
    reviewCount: 145,
  },
  {
    name: "Harbour View Hotel",
    address: "Anchor Road",
    town: "Bristol",
    postcode: "BS1 5LL",
    category: "hotel",
    description: "A boutique hotel overlooking Bristol's iconic harbour. We welcome dogs of all sizes with a dedicated welcome pack including a bed, bowls and local dog walking maps. A true home away from home.",
    phone: "0117 910 1234",
    website: "https://harbourviewhotel.co.uk",
    imageUrl: "/images/hotel1.jpg",
    dogPolicy: "dogs_inside",
    waterBowls: true,
    dogTreats: true,
    dogMenu: false,
    latitude: 51.4490,
    longitude: -2.5990,
    rating: 4.6,
    reviewCount: 87,
  },
  {
    name: "The Green Park Tearoom",
    address: "Green Park Station",
    town: "Bath",
    postcode: "BA1 1JB",
    category: "cafe",
    description: "Set in the stunning Victorian Green Park Station, this tearoom is a favourite of Bath's dog-walking community. Dogs are welcome throughout and we serve a selection of dog-friendly cakes.",
    phone: "01225 448899",
    website: "https://greenparktearooms.co.uk",
    imageUrl: "/images/cafe4.jpg",
    dogPolicy: "dogs_inside",
    waterBowls: true,
    dogTreats: true,
    dogMenu: false,
    latitude: 51.3782,
    longitude: -2.3709,
    rating: 4.5,
    reviewCount: 93,
  },
  {
    name: "Cotswold Country Supplies",
    address: "15 Sheep Street",
    town: "Burford",
    postcode: "OX18 4LP",
    category: "retail",
    description: "A wonderful country store stocking everything for the rural lifestyle. Dogs are always welcome and we have a huge pet section. Our staff are all dog owners who love meeting your pups.",
    phone: "01993 822334",
    website: "https://cotswoldcountrysupplies.co.uk",
    imageUrl: "/images/retail2.jpg",
    dogPolicy: "dogs_inside",
    waterBowls: true,
    dogTreats: true,
    dogMenu: false,
    latitude: 51.8067,
    longitude: -1.8380,
    rating: 4.4,
    reviewCount: 55,
  },
  {
    name: "The Old Mill",
    address: "Mill Lane",
    town: "Burford",
    postcode: "OX18 4RY",
    category: "pub",
    description: "A picturesque 16th century mill pub with a stunning mill-pond garden. Perfect for a post-walk pint with your dog. We have a dedicated dog menu with homemade sausages and rice.",
    phone: "01993 822556",
    website: "https://oldmillburford.co.uk",
    imageUrl: "/images/pub4.jpg",
    dogPolicy: "dogs_both",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.8032,
    longitude: -1.8410,
    rating: 4.7,
    reviewCount: 167,
  },
  {
    name: "Victoria Park Cafe",
    address: "Victoria Park",
    town: "Bristol",
    postcode: "BS3 4RR",
    category: "cafe",
    description: "A beloved park café right in the heart of Victoria Park. We cater specifically for dog walkers with a dedicated outdoor seating area, water stations and a range of treats for the pooches.",
    phone: "0117 963 0011",
    imageUrl: "/images/cafe5.jpg",
    dogPolicy: "dogs_outside",
    waterBowls: true,
    dogTreats: true,
    dogMenu: false,
    latitude: 51.4390,
    longitude: -2.5960,
    rating: 4.3,
    reviewCount: 72,
  },
  {
    name: "Tail & Terrace",
    address: "6 Regent Circus",
    town: "Swindon",
    postcode: "SN1 1PR",
    category: "restaurant",
    description: "Contemporary dining in Swindon with a beautifully landscaped dog-friendly terrace. Our weekend brunch is legendary and we always have puppuccinos and pupcakes available for our four-legged guests.",
    phone: "01793 221100",
    website: "https://tailandterrace.co.uk",
    imageUrl: "/images/restaurant3.jpg",
    dogPolicy: "dogs_outside",
    waterBowls: true,
    dogTreats: true,
    dogMenu: true,
    latitude: 51.5618,
    longitude: -1.7794,
    rating: 4.5,
    reviewCount: 109,
  },
];

export async function seedDatabase() {
  try {
    const count = await storage.getPlaceCount();
    if (count > 0) {
      console.log(`Database already seeded with ${count} places.`);
      return;
    }
    console.log("Seeding database with dog-friendly places...");
    for (const place of seedPlaces) {
      await storage.createPlace(place);
    }
    console.log(`Seeded ${seedPlaces.length} dog-friendly places.`);
  } catch (err) {
    console.error("Seed error:", err);
  }
}
